name: Production Build

run-name: Build on Node.js (${{ inputs.node-version }}) and ${{ inputs.runs-on == 'ubuntu-latest' && 'Ubuntu' || inputs.runs-on == 'windows-latest' && 'Windows' || inputs.runs-on == 'macos-latest' && 'macOS' }} (latest)

on:
  workflow_call:
    inputs:
      runs-on:
        description: Operating System (OS)
        type: string
        default: ubuntu-latest
      node-version:
        description: Node.js
        type: string
        default: 18.x
  workflow_dispatch:
    inputs:
      runs-on:
        description: Operating System (OS)
        type: choice
        options:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        default: ubuntu-latest
        required: true
      node-version:
        description: Node.js
        type: choice
        options:
          - 14.x
          - 16.x
          - 18.x
          - 20.x
        default: 18.x
        required: true

jobs:
  build:
    name: Node.js (${{ inputs.node-version }}) + ${{ inputs.runs-on == 'ubuntu-latest' && 'Ubuntu' || inputs.runs-on == 'windows-latest' && 'Windows' || inputs.runs-on == 'macos-latest' && 'macOS' }} (latest)

    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload production build artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: build
          if-no-files-found: error
