name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Code Linting
    uses: ./.github/workflows/code-linting.yml

  format:
    name: Code Formatting
    uses: ./.github/workflows/code-formatting.yml

  build:
    name: Production Build
    needs: [lint, format]
    uses: ./.github/workflows/production-build.yml

  test:
    name: Unit Testing
    needs: build
    uses: ./.github/workflows/unit-testing.yml
